config/routes.rb
Rails.application.routes.draw do
  resources :pokemons
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
end

app/models/move.rb
class Move < ApplicationRecord
end

app/models/poke_type.rb
class PokeType < ApplicationRecord
end

app/models/pokemon.rb
class Pokemon < ApplicationRecord
  has_one_attached :picture
  has_one_attached :sprite
end

app/models/pokemon_type.rb
class PokemonType < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

def home
  @pokes = Pokemon.all
end

end

app/controllers/pokemons_controller.rb
class PokemonsController < ApplicationController

def show
  @poke = Pokemon.find(params[:id])
  @types = PokemonType.where(pokemon_id: @poke.id)
  @moves = []
  @types.each do |x|
    r = Move.where(poke_type_id: x.poke_type_id)
    r.each {|y| @moves.push(y)}
  end
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PokemonApi</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h3><%= link_to "Pokedex", root_path %></h3>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<head>
<style>#dttb{width: 90%; position: relative; left: 100px;}</style>
<script>
$(document).ready(function() {
  var table = $("#dttb").DataTable();
  debugger;
  table.columns().every(function () {
    var that = this;
    $( 'input', this.footer() ).on('keyup change', function () {
        if ( that.search() !== this.value ) {
            that
                .search( this.value )
                .draw();
        }
    } );
} );
});
</script>
</head>
<h1>Pokedex</h1>

<table class="table" id="dttb">
<thead>
<tr>
<th>Name</th>
<th>HP</th>
<th>Attack</th>
<th>Defense</th>
<th>Special Attack</th>
<th>Special Defense</th>
<th>Speed</th>
<th>Type(s)</th>
</tr>
</thead>
<tbody>
<% @pokes.each do |x| %>
<tr>
  <td><%= link_to x.english_name, pokemon_path(x.id) %></td>
  <td><%= x.hp %></td>
  <td><%= x.attack %></td>
  <td><%= x.defense %></td>
  <td><%= x.sp_attack %></td>
  <td><%= x.sp_defense %></td>
  <td><%= x.speed %></td>
  <% r = PokemonType.select {|y| y.pokemon_id == x.id } %>
  <td>
  <% r.each do |q| %>
    <%= PokeType.find(q.poke_type_id).english_name %>
  <% end %>
  </td>
</tr>
<% end %>
</tbody>
<tfoot>
  <th type="text"><input class="form-control" type="text"></input></th>
  <th type="text"><input class="form-control"type="text"></input></th>
  <th type="text"><input class="form-control"type="text"></input></th>
  <th type="text"><input class="form-control"type="text"></input></th>
  <th type="text"><input class="form-control"type="text"></input></th>
  <th type="text"><input class="form-control" type="text"></input></th>
  <th type="text"><input class="form-control"type="text"></input></th>
  <th type="text"><input class="form-control"type="text"></input></th>
</tfoot>
</table>

app/views/pokemons/show.html.erb
<head>
<script>
$(document).ready(function() {
  var table = $("#dttb").DataTable();
  debugger;
  table.columns().every(function () {
    var that = this;
    $( 'input', this.footer() ).on('keyup change', function () {
        if ( that.search() !== this.value ) {
            that
                .search( this.value )
                .draw();
        }
    } );
} );
});
</script>
</head>
<center>
<%= image_tag url_for @poke.picture %>
<h4>English Name: <%= @poke.english_name %> | Japanese Name: <%= @poke.japanese_name %> | Chinese Name: <%= @poke.chinese_name %></h4>
<table class="table"style="width: 60%;">
<thead>
<tr>
<th>HP</th>
<th>Attack</th>
<th>Defense</th>
<th>Special Attack</th>
<th>Special Defense</th>
<th>Speed</th>
<th>Type(s)</th>
</tr>
</thead>
<tbody>
<tr>
  <td><%= @poke.hp %></td>
  <td><%= @poke.attack %></td>
  <td><%= @poke.defense %></td>
  <td><%= @poke.sp_attack %></td>
  <td><%= @poke.sp_defense %></td>
  <td><%= @poke.speed %></td>
  <% r = PokemonType.select {|y| y.pokemon_id == @poke.id } %>
  <td>
  <% r.each do |q| %>
    <%= PokeType.find(q.poke_type_id).english_name %>
    <% end %>
  </td>
</tr>
</tbody>
</table>
<h1>Available Moves</h1>
<table id="dttb" style="width: 70%;"class="table">
<thead>
<tr>
<th>Name</th>
<th>PP</th>
<th>Power</th>
<th>Accuracy</th>
<th>Move Type</th>
</tr>
</thead>
<tbody>
<% @moves.each do |x| %>
<tr>
  <td><%= x.name %></td>
  <td><%= x.pp %></td>
  <td><%= x.accuracy %></td>
  <td><%= x.power %></td>
  <td><%= x.move_type%></td>
</tr>
<% end %>
</tbody>
</table>

</center>